.TH RIVER 1 2020-06-04 github.com/ifreund/river "General Commands Manual"

.SH NAME
river \- dynamic tiling Wayland compositor

.SH SYNOPSIS
.BR river " [" -c
.IR shell_command ]

.SH DESCRIPTION
.B river
is a dynamic tiling Wayland compositor inspired by dwm and bspwm
based on wlroots and written in Zig.

.SH OPTIONS

.TP
.BI -c " shell_command"
Run a shell command or give the path to a script
that will be run before river gets started.
This is where you define keymaps using
.BR riverctl (1)
and autostart programs.
Make sure the script is executable.

.SH CONFIGURATION
View border width, gap sizes, and programs which should float are configured in
.IR Config.zig .
Make your changes and recompile.

.PP
Experimental XWayland support can be enabled on compile-time with the
.I -Dxwayland=true
flag.

Keyboard layout and other XKB options can be set in
.IR Keyboard.zig .

.SH SEE ALSO

.BR riverctl "(1), " bspwm "(1), " dwm (1)
